version: '3.3'

services:
  sonar:
    container_name: XpressBank-sonarqube
    image: sonarqube:10.3.0-community
    environment:
      - SONAR_FORCEAUTHENTICATION=false
    ports:
      - "9001:9000"
      - "9000:9000"
